/**
 * Documents Generator
 * Generates project documentation from Architect plan
 */
export type DocumentType = 'prd' | 'readme' | 'architecture' | 'roadmap' | 'setup'

export interface ArchitectPlan {
  name: string
  description: string
  type?: 'construct-space' | 'project'
  spaceId?: string
  spaceName?: string
  spaceScope?: 'project' | 'app' | 'both'
  spaceIcon?: string
  decisions: {
    platform?: string
    frontend?: string
    backend?: string
    database?: string
    auth?: string | string[]
    styling?: string
    hosting?: string
    [key: string]: string | string[] | undefined
  }
  techStack?: {
    framework?: string
    styling?: string
    animations?: string
    backend?: string
    database?: string
    hosting?: string
    key_libraries?: string[]
  }
  prd?: {
    overview?: string
    targetUsers?: string
    coreFeatures?: string[]
    techRationale?: string
    mvpScope?: string[]
    futureConsiderations?: string[]
    designNotes?: string
    sections?: string[]
    contentStructure?: string
  }
}

interface StackSnapshot {
  platform: string
  frontend: string
  backend: string
  database: string
  hosting: string
  styling: string
  animations: string
  libraries: string[]
  auth: string[]
}


export interface DocumentOption {
  type: DocumentType
  label: string
  description: string
  icon: string
  default: boolean
}

export const DOCUMENT_OPTIONS: DocumentOption[] = [
  {
    type: 'prd',
    label: 'PRD',
    description: 'Product Requirements Document with features and scope',
    icon: 'i-lucide-file-text',
    default: true
  },
  {
    type: 'readme',
    label: 'README',
    description: 'Project overview, tech stack, and getting started',
    icon: 'i-lucide-book-open',
    default: true
  },
  {
    type: 'architecture',
    label: 'ARCHITECTURE',
    description: 'Technical decisions and system design rationale',
    icon: 'i-lucide-git-branch',
    default: false
  },
  {
    type: 'roadmap',
    label: 'ROADMAP',
    description: 'MVP scope and future development phases',
    icon: 'i-lucide-map',
    default: false
  },
  {
    type: 'setup',
    label: 'SETUP',
    description: 'Development environment setup instructions',
    icon: 'i-lucide-settings',
    default: false
  }
]

/**
 * Generate PRD markdown
 */
export function generatePRD(plan: ArchitectPlan): string {
  const prd = plan.prd || {}
  const stack = getStackSnapshot(plan)

  return `# ${plan.name} PRD

## Product Summary
${prd.overview || plan.description || 'No description provided.'}

## Target Users
${prd.targetUsers || 'Define the primary audience, use cases, and user constraints.'}

## Product Shape
${formatDecisionHighlights(plan, stack)}

## Core Features
${formatList(prd.coreFeatures)}

## MVP Release Definition
${formatList(prd.mvpScope, true)}

## Delivery Tracks
${formatDeliveryTracks(plan, stack)}

## Definition of Done
${formatDefinitionOfDone(plan)}

## Technical Direction
${formatStackNarrative(plan, stack)}

## Technical Rationale
${prd.techRationale || 'Capture why this stack and architecture fit the initial release.'}

## Design Direction
${prd.designNotes || 'Document visual identity, motion, typography, and layout principles.'}
${prd.sections?.length ? `\n## Primary Screens / Sections\n${prd.sections.map((s, i) => `${i + 1}. ${s}`).join('\n')}` : ''}
${prd.contentStructure ? `\n## Content Structure\n${prd.contentStructure}` : ''}

## Future Considerations
${formatList(prd.futureConsiderations)}

---
*Generated by Construct Architect*
`
}

/**
 * Generate README markdown
 */
export function generateREADME(plan: ArchitectPlan): string {
  const prd = plan.prd || {}
  const stack = getStackSnapshot(plan)

  return `# ${plan.name}

${prd.overview || plan.description || ''}

## Product Snapshot

${formatDecisionHighlights(plan, stack)}

## Core Experience

${formatList(prd.coreFeatures)}

## Build Targets

${formatBuildTargets(plan, stack)}

## Tech Stack

${formatTechStackFromSnapshot(stack)}

${stack.libraries.length ? `## Key Libraries\n\n${stack.libraries.map(lib => `- ${lib}`).join('\n')}\n` : ''}## Getting Started

### Prerequisites

${getPrerequisites(plan)}

### Installation

\`\`\`bash
# Clone the repository
git clone <repository-url>
cd ${toKebabCase(plan.name)}

${getInstallCommand(plan)}
\`\`\`

### Run Locally

\`\`\`bash
${getDevCommand(plan)}
\`\`\`

## Delivery Scope

${formatList(prd.mvpScope, true)}

## Definition of Done

${formatDefinitionOfDone(plan)}

${prd.sections?.length ? `## Primary Screens / Sections\n\n${prd.sections.map((section, index) => `${index + 1}. ${section}`).join('\n')}\n` : ''}## Documentation

Project documentation lives in \`docs/\`.

- \`docs/${getDocumentFilename('prd', plan.name)}\` — product requirements and scope
- \`docs/${getDocumentFilename('readme', plan.name)}\` — project overview and setup
- Add \`architecture\`, \`roadmap\`, and \`setup\` docs when the project needs deeper operational detail

## Repository Structure

\`\`\`
${formatRepositoryStructure(plan, stack)}
\`\`\`

---
*Generated by Construct Architect*
`
}

/**
 * Generate ARCHITECTURE markdown
 */
export function generateARCHITECTURE(plan: ArchitectPlan): string {
  const decisions = plan.decisions || {}
  const prd = plan.prd || {}
  const stack = getStackSnapshot(plan)
  const platform = firstNonEmpty(decisions.platform, stack.platform)
  const frontend = firstNonEmpty(decisions.frontend, stack.frontend)
  const backend = firstNonEmpty(decisions.backend, stack.backend)
  const database = firstNonEmpty(decisions.database, stack.database)
  const auth = stack.auth.length > 0
    ? stack.auth
    : normalizeStringArray(decisions.auth)

  return `# Architecture

## Overview

This document outlines the technical architecture for ${plan.name}.

## Technology Choices

### Platform: ${platform || 'Not specified'}
${getPlatformRationale(platform)}

### Frontend: ${frontend || 'Not specified'}
${getFrontendRationale(frontend)}

### Backend: ${backend || 'Not specified'}
${getBackendRationale(backend)}

### Database: ${database || 'Not specified'}
${getDatabaseRationale(database)}

### Authentication
${formatList(auth)}

## Technical Rationale

${prd.techRationale || 'The technology choices were made based on project requirements, team expertise, and scalability needs.'}

${prd.designNotes ? `## Design Direction\n\n${prd.designNotes}\n` : ''}
## System Diagram

\`\`\`
┌─────────────┐     ┌─────────────┐     ┌─────────────┐
│   Client    │────▶│   Server    │────▶│  Database   │
│ ${(frontend || 'Frontend').padEnd(11)}│     │ ${(backend || 'Backend').padEnd(11)}│     │ ${(database || 'DB').padEnd(11)}│
└─────────────┘     └─────────────┘     └─────────────┘
\`\`\`

## Security Considerations

- Authentication: ${auth.length > 0 ? auth.join(', ') : 'To be defined'}
- Data validation at API boundaries
- Environment-based configuration
- Secrets management

## Scalability

- Horizontal scaling via containerization
- Database connection pooling
- Caching strategy (if applicable)

---
*Generated by Construct Architect*
`
}

/**
 * Generate ROADMAP markdown
 */
export function generateROADMAP(plan: ArchitectPlan): string {
  const prd = plan.prd || {}

  return `# Roadmap

## ${plan.name}

### Phase 1: MVP
${formatList(prd.mvpScope, true)}

### Phase 2: Core Features
${formatList(prd.coreFeatures, true)}

### Phase 3: Future Enhancements
${formatList(prd.futureConsiderations, true)}

## Milestones

| Phase | Goal | Status |
|-------|------|--------|
| Phase 1 | MVP Launch | 🔄 In Progress |
| Phase 2 | Feature Complete | ⏳ Planned |
| Phase 3 | Enhancements | 📋 Backlog |

---
*Generated by Construct Architect*
`
}

/**
 * Generate SETUP markdown
 */
export function generateSETUP(plan: ArchitectPlan): string {
  const stack = getStackSnapshot(plan)

  return `# Development Setup

## Prerequisites

${getPrerequisites(plan)}

## Environment Setup

### 1. Clone Repository

\`\`\`bash
git clone <repository-url>
cd ${toKebabCase(plan.name)}
\`\`\`

### 2. Install Dependencies

\`\`\`bash
${getInstallCommand(plan)}
\`\`\`

### 3. Environment Variables

Create a \`.env\` file:

\`\`\`env
# App
APP_NAME=${plan.name}
NODE_ENV=development

# Database
DATABASE_URL=

# Auth
${getAuthEnvVars(stack.auth)}
\`\`\`

### 4. Database Setup

\`\`\`bash
${getDatabaseSetupCommandForStack(stack)}
\`\`\`

### 5. Start Development

\`\`\`bash
${getDevCommand(plan)}
\`\`\`

## IDE Setup

Recommended extensions:
${getIDEExtensionsForStack(stack)}

## Troubleshooting

- **Port in use**: Check if another process is using the port
- **Database connection**: Verify DATABASE_URL is correct
- **Dependencies**: Try removing node_modules and reinstalling

---
*Generated by Construct Architect*
`
}

/**
 * Generate document by type
 */
export function generateDocument(type: DocumentType, plan: ArchitectPlan): string {
  switch (type) {
    case 'prd':
      return generatePRD(plan)
    case 'readme':
      return generateREADME(plan)
    case 'architecture':
      return generateARCHITECTURE(plan)
    case 'roadmap':
      return generateROADMAP(plan)
    case 'setup':
      return generateSETUP(plan)
    default:
      throw new Error(`Unknown document type: ${type}`)
  }
}

/**
 * Generate multiple documents
 */
export function generateDocuments(
  types: DocumentType[],
  plan: ArchitectPlan
): Record<DocumentType, string> {
  const docs: Partial<Record<DocumentType, string>> = {}
  for (const type of types) {
    docs[type] = generateDocument(type, plan)
  }
  return docs as Record<DocumentType, string>
}

/**
 * Get filename for document type
 */
export function getDocumentFilename(type: DocumentType, projectName?: string): string {
  if (projectName && projectName.trim()) {
    const title = getDocumentTitle(type, projectName)
    return `${toKebabCase(title)}.md`
  }

  switch (type) {
    case 'prd':
      return 'prd.md'
    case 'readme':
      return 'readme.md'
    case 'architecture':
      return 'architecture.md'
    case 'roadmap':
      return 'roadmap.md'
    case 'setup':
      return 'setup.md'
  }
}

/**
 * Get document title for type and project name.
 * This is shared by API document titles and local filename generation.
 */
export function getDocumentTitle(type: DocumentType, projectName: string): string {
  const name = projectName.trim() || 'Project'
  switch (type) {
    case 'prd':
      return name
    case 'readme':
      return `${name} - README`
    case 'architecture':
      return `${name} - Architecture`
    case 'roadmap':
      return `${name} - Roadmap`
    case 'setup':
      return `${name} - Setup`
  }
}

// Helper functions

function formatTechStackFromArchitect(ts: NonNullable<ArchitectPlan['techStack']>): string {
  const items: string[] = []
  if (ts.framework) items.push(`- **Framework**: ${ts.framework}`)
  if (ts.styling) items.push(`- **Styling**: ${ts.styling}`)
  if (ts.animations) items.push(`- **Animations**: ${ts.animations}`)
  if (ts.backend) items.push(`- **Backend**: ${ts.backend}`)
  if (ts.database) items.push(`- **Database**: ${ts.database}`)
  if (ts.hosting) items.push(`- **Hosting**: ${ts.hosting}`)
  if (ts.key_libraries?.length) items.push(`- **Key Libraries**: ${ts.key_libraries.join(', ')}`)
  return items.length ? items.join('\n') : 'Not specified'
}

function getStackSnapshot(plan: ArchitectPlan): StackSnapshot {
  const decisions = plan.decisions || {}
  const techStack = plan.techStack || {}
  const projectText = getPlanNarrativeText(plan)

  return {
    platform: firstNonEmpty(decisions.platform, inferPlatformFromText(projectText)),
    frontend: firstNonEmpty(decisions.frontend, techStack.framework, inferFrontendFromText(projectText)),
    backend: firstNonEmpty(decisions.backend, techStack.backend, inferBackendFromText(projectText)),
    database: firstNonEmpty(decisions.database, techStack.database, inferDatabaseFromText(projectText)),
    hosting: firstNonEmpty(decisions.hosting, techStack.hosting, inferHostingFromText(projectText)),
    styling: firstNonEmpty(decisions.styling, techStack.styling),
    animations: firstNonEmpty(techStack.animations, inferAnimationApproachFromText(projectText)),
    libraries: uniqueValues([...(techStack.key_libraries || []), ...inferLibrariesFromText(projectText)]),
    auth: normalizeStringArray(decisions.auth),
  }
}

function formatTechStackFromSnapshot(stack: StackSnapshot): string {
  const items: string[] = []
  if (stack.platform) items.push(`- **Platform**: ${stack.platform}`)
  if (stack.frontend) items.push(`- **Frontend**: ${stack.frontend}`)
  if (stack.backend) items.push(`- **Backend**: ${stack.backend}`)
  if (stack.database) items.push(`- **Database**: ${stack.database}`)
  if (stack.styling) items.push(`- **Styling**: ${stack.styling}`)
  if (stack.animations) items.push(`- **Animations**: ${stack.animations}`)
  if (stack.hosting) items.push(`- **Hosting**: ${stack.hosting}`)
  return items.length ? items.join('\n') : 'Not specified'
}

function formatDecisionHighlights(plan: ArchitectPlan, stack: StackSnapshot): string {
  const highlights: string[] = []
  if (stack.platform) highlights.push(`- **Platform**: ${stack.platform}`)
  if (stack.frontend) highlights.push(`- **Frontend**: ${stack.frontend}`)
  if (stack.backend) highlights.push(`- **Backend**: ${stack.backend}`)
  if (stack.database) highlights.push(`- **Database**: ${stack.database}`)
  if (stack.auth.length > 0) highlights.push(`- **Authentication**: ${stack.auth.join(', ')}`)
  if (stack.hosting) highlights.push(`- **Hosting**: ${stack.hosting}`)
  const spaces = Array.isArray(plan.decisions?.spaces) ? plan.decisions.spaces : []
  if (spaces.length > 0) highlights.push(`- **Construct Spaces**: ${spaces.join(', ')}`)
  return highlights.length ? highlights.join('\n') : '- Product direction still needs to be defined.'
}

function formatStackNarrative(plan: ArchitectPlan, stack: StackSnapshot): string {
  const parts: string[] = []
  if (plan.techStack?.framework) parts.push(`**Framework:** ${plan.techStack.framework}`)
  if (plan.techStack?.backend) parts.push(`**Backend:** ${plan.techStack.backend}`)
  if (plan.techStack?.database) parts.push(`**Database:** ${plan.techStack.database}`)
  if (plan.techStack?.styling) parts.push(`**Styling:** ${plan.techStack.styling}`)
  if (plan.techStack?.animations) parts.push(`**Animations:** ${plan.techStack.animations}`)
  if (plan.techStack?.hosting) parts.push(`**Hosting:** ${plan.techStack.hosting}`)
  if (plan.techStack?.key_libraries?.length) parts.push(`**Key libraries:** ${plan.techStack.key_libraries.join(', ')}`)

  if (parts.length > 0) return parts.join('\n\n')
  return formatBuildTargets(plan, stack)
}

function formatTechStack(decisions: ArchitectPlan['decisions']): string {
  const items: string[] = []
  if (decisions.platform) items.push(`- **Platform**: ${decisions.platform}`)
  if (decisions.frontend) items.push(`- **Frontend**: ${decisions.frontend}`)
  if (decisions.backend) items.push(`- **Backend**: ${decisions.backend}`)
  if (decisions.database) items.push(`- **Database**: ${decisions.database}`)
  if (decisions.auth?.length) items.push(`- **Auth**: ${Array.isArray(decisions.auth) ? decisions.auth.join(', ') : decisions.auth}`)
  if (decisions.styling) items.push(`- **Styling**: ${decisions.styling}`)
  if (decisions.hosting) items.push(`- **Hosting**: ${decisions.hosting}`)
  return items.length ? items.join('\n') : 'Not specified'
}

function formatList(items?: string | string[], asChecklist = false): string {
  if (!items?.length) return 'To be defined.'
  const arr = Array.isArray(items) ? items : [items]
  const prefix = asChecklist ? '- [ ] ' : '- '
  return arr.map(item => `${prefix}${item}`).join('\n')
}

function formatBuildTargets(plan: ArchitectPlan, stack: StackSnapshot): string {
  const targets: string[] = []
  if (stack.frontend) {
    const platformSuffix = stack.platform ? ` for ${stack.platform.toLowerCase()} users` : ''
    targets.push(`- **Primary client**: ${stack.frontend}${platformSuffix}`)
  }
  if (stack.backend) {
    const persistence = stack.database ? ` backed by ${stack.database}` : ''
    targets.push(`- **Backend/API**: ${stack.backend}${persistence}`)
  }
  if (stack.auth.length > 0) {
    targets.push(`- **Authentication**: ${stack.auth.join(', ')}`)
  }
  if (stack.hosting) {
    targets.push(`- **Deployment target**: ${stack.hosting}`)
  }
  if (targets.length > 0) return targets.join('\n')

  return `- **Primary goal**: ${plan.description || 'Capture the app shape and implementation approach.'}`
}

function formatDeliveryTracks(plan: ArchitectPlan, stack: StackSnapshot): string {
  const prd = plan.prd || {}
  const sectionsSummary = summarizeTextList(prd.sections, 4)
  const featureSummary = summarizeTextList(prd.coreFeatures, 4)
  const mvpSummary = summarizeTextList(prd.mvpScope, 4)
  const blocks: string[] = []

  blocks.push(`### Product Owner
- Lock the MVP around ${mvpSummary || featureSummary || 'the documented core flow and launch checklist'}.
- Use the Definition of Done checklist below to decide when the first release is complete.`)

  blocks.push(`### Design
- Translate the product into polished flows for ${sectionsSummary || 'the primary screens and happy-path journeys'}.
- Follow the design direction in this PRD for visual language, typography, spacing, and motion.`)

  if (stack.frontend) {
    const libraryNote = stack.libraries.length > 0 ? ` using ${stack.libraries.join(', ')}` : ''
    blocks.push(`### Frontend / Client
- Implement the user-facing experience in ${stack.frontend}${libraryNote}.
- Cover the core interaction set: ${featureSummary || sectionsSummary || 'sign-in, discovery, creation, and management flows'}.`)
  }

  if (stack.backend || stack.database) {
    const backendLabel = stack.backend || 'API services'
    const databaseLabel = stack.database ? ` with ${stack.database}` : ''
    blocks.push(`### Backend
- Build ${backendLabel}${databaseLabel} to support the MVP flows end to end.
- Define data contracts, validation, and persistence for ${mvpSummary || featureSummary || 'the core launch scope'}.`)
  }

  blocks.push(`### DevOps
- Prepare local, staging, and production environments${stack.hosting ? ` with ${stack.hosting} as the initial deployment target` : ''}.
- Ship with environment config, secrets handling, logging, and a release checklist that matches the MVP scope.`)

  return blocks.join('\n\n')
}

function formatDefinitionOfDone(plan: ArchitectPlan): string {
  const prd = plan.prd || {}
  const baseline = Array.isArray(prd.mvpScope) && prd.mvpScope.length > 0
    ? prd.mvpScope
    : Array.isArray(prd.coreFeatures) && prd.coreFeatures.length > 0
      ? prd.coreFeatures
      : ['Core user journey implemented', 'Regression pass completed', 'Project docs updated']

  const items = baseline.slice(0, 8).map(item => `- [ ] ${item}`)
  items.push('- [ ] PRD and README reflect the shipped scope')
  items.push('- [ ] Launch checklist reviewed by product, design, engineering, and operations')
  return items.join('\n')
}

function formatRepositoryStructure(plan: ArchitectPlan, stack: StackSnapshot): string {
  const lines = [`${plan.name}/`, '├── docs/                # Product and technical documents']
  const frontend = `${stack.frontend} ${stack.platform}`.toLowerCase()
  const hasBackend = Boolean(stack.backend)

  if (frontend.includes('flutter') || frontend.includes('react native') || frontend.includes('expo')) {
    lines.push('├── code/')
    lines.push('│   ├── frontend/        # Mobile application')
    if (hasBackend) lines.push('│   └── backend/         # API and supporting services')
    lines.push('├── assets/              # App icons, images, and media')
    lines.push('├── tests/               # Automated tests')
    lines.push('└── README.md')
    return lines.join('\n')
  }

  if (hasBackend) {
    lines.push('├── code/')
    lines.push('│   ├── frontend/        # Client application')
    lines.push('│   └── backend/         # API, workers, and integrations')
    lines.push('├── tests/               # Automated tests')
    lines.push('└── README.md')
    return lines.join('\n')
  }

  lines.push('├── src/                 # Application source')
  lines.push('├── public/              # Static assets')
  lines.push('├── tests/               # Automated tests')
  lines.push('└── README.md')
  return lines.join('\n')
}

function firstNonEmpty(...values: Array<string | undefined>): string {
  for (const value of values) {
    if (typeof value === 'string' && value.trim()) return value.trim()
  }
  return ''
}

function getPlanNarrativeText(plan: ArchitectPlan): string {
  const prd = plan.prd || {}
  const decisionValues = Object.values(plan.decisions || {}).flatMap(value => normalizeStringArray(value))
  const techValues = normalizeStringArray([
    plan.techStack?.framework,
    plan.techStack?.styling,
    plan.techStack?.animations,
    plan.techStack?.backend,
    plan.techStack?.database,
    plan.techStack?.hosting,
    ...(plan.techStack?.key_libraries || []),
  ])

  return [
    plan.name,
    plan.description,
    prd.overview,
    prd.targetUsers,
    prd.techRationale,
    prd.designNotes,
    prd.contentStructure,
    ...normalizeStringArray(prd.coreFeatures),
    ...normalizeStringArray(prd.mvpScope),
    ...normalizeStringArray(prd.futureConsiderations),
    ...normalizeStringArray(prd.sections),
    ...decisionValues,
    ...techValues,
  ]
    .filter(Boolean)
    .join(' ')
}

function inferPlatformFromText(text: string): string {
  return inferNamedChoice(text, [
    [/\bflutter\b|\breact[\s-]?native\b|\bexpo\b|\bios\b|\bandroid\b|\bmobile\b/i, 'Mobile'],
    [/\btauri\b|\belectron\b|\bdesktop\b/i, 'Desktop'],
    [/\bnext(?:\.js)?\b|\bnuxt\b|\breact\b|\bvue\b|\bastro\b|\bweb\b|\bwebsite\b|\blanding page\b|\bsaas\b|\bdashboard\b/i, 'Web'],
  ])
}

function inferFrontendFromText(text: string): string {
  if (/\bflutter\b/i.test(text)) {
    return /\bgetx\b/i.test(text) ? 'Flutter (GetX)' : 'Flutter'
  }
  return inferNamedChoice(text, [
    [/\bexpo\b/i, 'Expo'],
    [/\breact[\s-]?native\b/i, 'React Native'],
    [/\bnext(?:\.js)?\b/i, 'Next.js'],
    [/\bnuxt\b/i, 'Nuxt'],
    [/\bvue\b/i, 'Vue'],
    [/\breact\b/i, 'React'],
    [/\btauri\b/i, 'Tauri'],
  ])
}

function inferBackendFromText(text: string): string {
  return inferNamedChoice(text, [
    [/\bgin\b|\bfiber\b|\becho\b|\bchi\b|\bgolang\b|\bgo backend\b|\bgo api\b|\bgo\b/i, 'Go'],
    [/\bfastapi\b/i, 'FastAPI'],
    [/\bexpress(?:\.js)?\b|\bnode(?:\.js)?\b/i, 'Node.js / Express'],
    [/\bnest(?:\.js)?\b/i, 'NestJS'],
    [/\bdjango\b/i, 'Django'],
    [/\blaravel\b/i, 'Laravel'],
    [/\brails\b/i, 'Rails'],
  ])
}

function inferDatabaseFromText(text: string): string {
  return inferNamedChoice(text, [
    [/\bsupabase\b/i, 'Supabase / PostgreSQL'],
    [/\bpostgres(?:ql)?\b/i, 'PostgreSQL'],
    [/\bsqlite\b/i, 'SQLite'],
    [/\bmysql\b/i, 'MySQL'],
    [/\bmongo(?:db)?\b/i, 'MongoDB'],
    [/\bfirebase\b/i, 'Firebase'],
  ])
}

function inferHostingFromText(text: string): string {
  return inferNamedChoice(text, [
    [/\bvercel\b/i, 'Vercel'],
    [/\bnetlify\b/i, 'Netlify'],
    [/\bfly\.io\b|\bfly io\b/i, 'Fly.io'],
    [/\brender\b/i, 'Render'],
    [/\brailway\b/i, 'Railway'],
    [/\baws\b/i, 'AWS'],
    [/\bcloudflare\b/i, 'Cloudflare'],
    [/\bfirebase\b/i, 'Firebase'],
    [/\bapp store\b|\bplay store\b/i, 'App Store / Play Store'],
  ])
}

function inferAnimationApproachFromText(text: string): string {
  return inferNamedChoice(text, [
    [/\breal[-\s]?time chat\b|\breal[-\s]?time\b|\blive updates?\b/i, 'Realtime updates and event-driven UI feedback'],
    [/\benergetic\b|\bsporty\b|\bplayful\b|\bbouncy\b/i, 'Snappy motion with spring-based transitions'],
    [/\bsubtle\b|\bminimal\b/i, 'Subtle motion and micro-interactions'],
  ])
}

function inferLibrariesFromText(text: string): string[] {
  const inferred: string[] = []
  if (/\bgetx\b/i.test(text)) inferred.push('GetX')
  if (/\briverpod\b/i.test(text)) inferred.push('Riverpod')
  if (/\bbloc\b/i.test(text)) inferred.push('flutter_bloc')
  if (/\bdio\b/i.test(text)) inferred.push('Dio')
  if (/\bsupabase\b/i.test(text)) inferred.push('Supabase')
  if (/\bfirebase\b/i.test(text)) inferred.push('Firebase')
  if (/\bmapbox\b/i.test(text)) inferred.push('Mapbox')
  if (/\bgoogle maps?\b/i.test(text)) inferred.push('Google Maps')
  if (/\breal[-\s]?time chat\b|\bwebsocket\b/i.test(text)) inferred.push('WebSocket transport')
  return inferred
}

function inferNamedChoice(text: string, patterns: Array<[RegExp, string]>): string {
  for (const [pattern, label] of patterns) {
    if (pattern.test(text)) return label
  }
  return ''
}

function normalizeStringArray(value?: string | string[] | Array<string | undefined>): string[] {
  if (!value) return []
  const items = Array.isArray(value) ? value : [value]
  return items
    .flatMap(item => typeof item === 'string' ? [item] : [])
    .map(item => item.trim())
    .filter(Boolean)
}

function uniqueValues(items: string[]): string[] {
  return Array.from(new Set(items.map(item => item.trim()).filter(Boolean)))
}

function summarizeTextList(items?: string[], limit = 3): string {
  if (!Array.isArray(items) || items.length === 0) return ''
  const normalized = items.map(item => item.trim()).filter(Boolean)
  if (normalized.length === 0) return ''
  if (normalized.length <= limit) return normalized.join(', ')
  return `${normalized.slice(0, limit).join(', ')}, and ${normalized.length - limit} more`
}

function toKebabCase(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

function getPrerequisites(plan: ArchitectPlan): string {
  const stack = getStackSnapshot(plan)
  const prereqs: string[] = []
  const frontend = `${stack.frontend} ${stack.platform}`.toLowerCase()
  const backend = stack.backend.toLowerCase()

  if (frontend.includes('node') || frontend.includes('nuxt') || frontend.includes('next') || frontend.includes('react') || frontend.includes('vue')) {
    prereqs.push('- Node.js 18+ and npm/bun')
  }
  if (frontend.includes('flutter')) {
    prereqs.push('- Flutter SDK 3.24+')
    prereqs.push('- Dart SDK (bundled with Flutter)')
  }
  if (frontend.includes('react native')) {
    prereqs.push('- Node.js 18+ and npm/yarn')
    prereqs.push('- React Native Android/iOS toolchain')
  }
  if (backend.includes('go') || backend.includes('gin')) {
    prereqs.push('- Go 1.21+')
  }
  if (backend.includes('python') || backend.includes('fastapi') || backend.includes('django')) {
    prereqs.push('- Python 3.11+')
  }
  if (stack.database.toLowerCase().includes('postgres')) {
    prereqs.push('- PostgreSQL 15+')
  }
  if (stack.database.toLowerCase().includes('mysql')) {
    prereqs.push('- MySQL 8+')
  }
  if (stack.database.toLowerCase().includes('mongo')) {
    prereqs.push('- MongoDB 6+')
  }

  return prereqs.length ? prereqs.join('\n') : '- Node.js 18+'
}

function getInstallCommand(plan: ArchitectPlan): string {
  const stack = getStackSnapshot(plan)
  const frontend = `${stack.frontend} ${stack.platform}`.toLowerCase()
  const backend = stack.backend.toLowerCase()
  const commands: string[] = []

  if (frontend.includes('flutter')) {
    commands.push('# Mobile app dependencies')
    commands.push('flutter pub get')
  } else if (frontend.includes('nuxt') || frontend.includes('vue')) {
    commands.push('# Frontend dependencies')
    commands.push('bun install')
  } else if (frontend.includes('next') || frontend.includes('react native') || frontend.includes('react')) {
    commands.push('# Frontend dependencies')
    commands.push('npm install')
  }

  if (backend.includes('go')) {
    commands.push('')
    commands.push('# Backend dependencies')
    commands.push('go mod tidy')
  } else if (backend.includes('node') || backend.includes('express')) {
    commands.push('')
    commands.push('# Backend dependencies')
    commands.push('npm install')
  }

  return commands.filter((line, index, arr) => !(line === '' && (index === 0 || arr[index - 1] === ''))).join('\n') || 'npm install'
}

function getDevCommand(plan: ArchitectPlan): string {
  const stack = getStackSnapshot(plan)
  const frontend = `${stack.frontend} ${stack.platform}`.toLowerCase()
  const backend = stack.backend.toLowerCase()
  const commands: string[] = []

  if (frontend.includes('flutter')) {
    commands.push('# Start the Flutter app')
    commands.push('flutter run')
  } else if (frontend.includes('nuxt') || frontend.includes('vue')) {
    commands.push('# Start the frontend')
    commands.push('bun run dev')
  } else if (frontend.includes('next')) {
    commands.push('# Start the frontend')
    commands.push('npm run dev')
  } else if (frontend.includes('react native')) {
    commands.push('# Start Metro / the mobile app')
    commands.push('npm run start')
  } else if (frontend.includes('react')) {
    commands.push('# Start the frontend')
    commands.push('npm run dev')
  }

  if (backend.includes('go')) {
    commands.push('')
    commands.push('# Start the API')
    commands.push('go run ./cmd/api')
  } else if (backend.includes('node') || backend.includes('express')) {
    commands.push('')
    commands.push('# Start the API')
    commands.push('npm run api:dev')
  }

  return commands.filter((line, index, arr) => !(line === '' && (index === 0 || arr[index - 1] === ''))).join('\n') || 'npm run dev'
}

function getPlatformRationale(platform?: string): string {
  if (!platform) return ''
  const p = platform.toLowerCase()
  if (p.includes('web')) return 'Web platform chosen for broad accessibility and rapid deployment.'
  if (p.includes('mobile')) return 'Mobile-first approach for on-the-go user experience.'
  if (p.includes('desktop')) return 'Desktop application for enhanced performance and offline capabilities.'
  return ''
}

function getFrontendRationale(frontend?: string): string {
  if (!frontend) return ''
  const f = frontend.toLowerCase()
  if (f.includes('nuxt')) return 'Nuxt 3 provides SSR, auto-imports, and excellent Vue DX.'
  if (f.includes('next')) return 'Next.js offers React SSR with great performance optimization.'
  if (f.includes('react')) return 'React ecosystem provides flexibility and wide community support.'
  if (f.includes('vue')) return 'Vue offers gentle learning curve and great reactivity system.'
  return ''
}

function getBackendRationale(backend?: string): string {
  if (!backend) return ''
  const b = backend.toLowerCase()
  if (b.includes('go') || b.includes('gin')) return 'Go provides excellent performance and simple concurrency.'
  if (b.includes('node') || b.includes('express')) return 'Node.js allows JavaScript full-stack development.'
  if (b.includes('python') || b.includes('fastapi')) return 'Python offers rapid development and rich ecosystem.'
  return ''
}

function getDatabaseRationale(database?: string): string {
  if (!database) return ''
  const d = database.toLowerCase()
  if (d.includes('postgres')) return 'PostgreSQL provides robust ACID compliance and extensibility.'
  if (d.includes('mysql')) return 'MySQL offers proven reliability and wide hosting support.'
  if (d.includes('mongo')) return 'MongoDB provides flexible schema for evolving data models.'
  if (d.includes('sqlite')) return 'SQLite offers simplicity for embedded or small-scale applications.'
  return ''
}

function getAuthEnvVars(auth?: string | string[]): string {
  if (!auth?.length) return '# AUTH_SECRET='
  const authArray = Array.isArray(auth) ? auth : [auth]
  const vars: string[] = []
  for (const a of authArray) {
    const lower = a.toLowerCase()
    if (lower.includes('oauth') || lower.includes('google')) vars.push('GOOGLE_CLIENT_ID=\nGOOGLE_CLIENT_SECRET=')
    if (lower.includes('github')) vars.push('GITHUB_CLIENT_ID=\nGITHUB_CLIENT_SECRET=')
    if (lower.includes('jwt') || lower.includes('email')) vars.push('JWT_SECRET=')
  }
  return vars.length ? vars.join('\n') : 'AUTH_SECRET='
}

function getDatabaseSetupCommand(decisions: ArchitectPlan['decisions']): string {
  const db = decisions.database?.toLowerCase() || ''
  const backend = decisions.backend?.toLowerCase() || ''
  const migrateCommand = backend.includes('go') ? 'go run ./cmd/migrate' : 'npm run db:migrate'
  if (db.includes('postgres')) return `# Create database\ncreatedb myapp_dev\n\n# Run migrations\n${migrateCommand}`
  if (db.includes('mysql')) return `# Create database\nmysql -e "CREATE DATABASE myapp_dev;"\n\n# Run migrations\n${migrateCommand}`
  if (db.includes('sqlite')) return `# SQLite will create file automatically\n${migrateCommand}`
  return '# Setup your database\nnpm run db:setup'
}

function getIDEExtensions(decisions: ArchitectPlan['decisions']): string {
  const exts: string[] = ['- ESLint', '- Prettier']
  const frontend = decisions.frontend?.toLowerCase() || ''
  const backend = decisions.backend?.toLowerCase() || ''

  if (frontend.includes('flutter')) exts.push('- Dart', '- Flutter')
  if (frontend.includes('vue') || frontend.includes('nuxt')) exts.push('- Volar (Vue)')
  if (frontend.includes('react') || frontend.includes('next')) exts.push('- ES7+ React snippets')
  if (backend.includes('go')) exts.push('- Go')
  if (backend.includes('python')) exts.push('- Python', '- Pylance')

  return exts.join('\n')
}

function getDatabaseSetupCommandForStack(stack: StackSnapshot): string {
  return getDatabaseSetupCommand({
    database: stack.database,
    backend: stack.backend,
  })
}

function getIDEExtensionsForStack(stack: StackSnapshot): string {
  return getIDEExtensions({
    frontend: stack.frontend,
    backend: stack.backend,
  })
}
