/**
 * Documents Generator
 * Generates project documentation from Architect plan
 */

export interface ArchitectPlan {
  name: string
  description: string
  type?: 'construct-space' | 'project'
  spaceId?: string
  spaceName?: string
  spaceScope?: 'project' | 'app' | 'both'
  spaceIcon?: string
  decisions: {
    platform?: string
    frontend?: string
    backend?: string
    database?: string
    auth?: string | string[]
    styling?: string
    hosting?: string
    [key: string]: string | string[] | undefined
  }
  prd?: {
    overview?: string
    targetUsers?: string
    coreFeatures?: string[]
    techRationale?: string
    mvpScope?: string[]
    futureConsiderations?: string[]
  }
}

export type DocumentType = 'prd' | 'readme' | 'architecture' | 'roadmap' | 'setup'

export interface DocumentOption {
  type: DocumentType
  label: string
  description: string
  icon: string
  default: boolean
}

export const DOCUMENT_OPTIONS: DocumentOption[] = [
  {
    type: 'prd',
    label: 'PRD',
    description: 'Product Requirements Document with features and scope',
    icon: 'i-lucide-file-text',
    default: true
  },
  {
    type: 'readme',
    label: 'README',
    description: 'Project overview, tech stack, and getting started',
    icon: 'i-lucide-book-open',
    default: true
  },
  {
    type: 'architecture',
    label: 'ARCHITECTURE',
    description: 'Technical decisions and system design rationale',
    icon: 'i-lucide-git-branch',
    default: false
  },
  {
    type: 'roadmap',
    label: 'ROADMAP',
    description: 'MVP scope and future development phases',
    icon: 'i-lucide-map',
    default: false
  },
  {
    type: 'setup',
    label: 'SETUP',
    description: 'Development environment setup instructions',
    icon: 'i-lucide-settings',
    default: false
  }
]

/**
 * Generate PRD markdown
 */
export function generatePRD(plan: ArchitectPlan): string {
  const prd = plan.prd || {}
  const decisions = plan.decisions || {}

  return `# ${plan.name}

## Overview
${prd.overview || plan.description || 'No description provided.'}

## Target Users
${prd.targetUsers || 'To be defined.'}

## Tech Stack
${formatTechStack(decisions)}

## Core Features
${formatList(prd.coreFeatures)}

## MVP Scope
${formatList(prd.mvpScope)}

## Technical Rationale
${prd.techRationale || 'See ARCHITECTURE.md for technical decisions.'}

## Future Considerations
${formatList(prd.futureConsiderations)}

---
*Generated by Construct Architect*
`
}

/**
 * Generate README markdown
 */
export function generateREADME(plan: ArchitectPlan): string {
  const decisions = plan.decisions || {}

  return `# ${plan.name}

${plan.description || ''}

## Tech Stack

${formatTechStack(decisions)}

## Getting Started

### Prerequisites

${getPrerequisites(decisions)}

### Installation

\`\`\`bash
# Clone the repository
git clone <repository-url>
cd ${toKebabCase(plan.name)}

# Install dependencies
${getInstallCommand(decisions)}

# Start development server
${getDevCommand(decisions)}
\`\`\`

## Project Structure

\`\`\`
${plan.name}/
├── docs/           # Documentation
├── src/            # Source code
├── tests/          # Test files
└── README.md
\`\`\`

## Documentation

Project documentation is generated in the \`docs/\` directory.

- Product requirements and planning docs
- Architecture and setup guides

## License

MIT

---
*Generated by Construct Architect*
`
}

/**
 * Generate ARCHITECTURE markdown
 */
export function generateARCHITECTURE(plan: ArchitectPlan): string {
  const decisions = plan.decisions || {}
  const prd = plan.prd || {}

  return `# Architecture

## Overview

This document outlines the technical architecture for ${plan.name}.

## Technology Choices

### Platform: ${decisions.platform || 'Not specified'}
${getPlatformRationale(decisions.platform)}

### Frontend: ${decisions.frontend || 'Not specified'}
${getFrontendRationale(decisions.frontend)}

### Backend: ${decisions.backend || 'Not specified'}
${getBackendRationale(decisions.backend)}

### Database: ${decisions.database || 'Not specified'}
${getDatabaseRationale(decisions.database)}

### Authentication
${formatList(decisions.auth)}

## Technical Rationale

${prd.techRationale || 'The technology choices were made based on project requirements, team expertise, and scalability needs.'}

## System Diagram

\`\`\`
┌─────────────┐     ┌─────────────┐     ┌─────────────┐
│   Client    │────▶│   Server    │────▶│  Database   │
│ ${(decisions.frontend || 'Frontend').padEnd(11)}│     │ ${(decisions.backend || 'Backend').padEnd(11)}│     │ ${(decisions.database || 'DB').padEnd(11)}│
└─────────────┘     └─────────────┘     └─────────────┘
\`\`\`

## Security Considerations

- Authentication: ${Array.isArray(decisions.auth) ? decisions.auth.join(', ') : decisions.auth || 'To be defined'}
- Data validation at API boundaries
- Environment-based configuration
- Secrets management

## Scalability

- Horizontal scaling via containerization
- Database connection pooling
- Caching strategy (if applicable)

---
*Generated by Construct Architect*
`
}

/**
 * Generate ROADMAP markdown
 */
export function generateROADMAP(plan: ArchitectPlan): string {
  const prd = plan.prd || {}

  return `# Roadmap

## ${plan.name}

### Phase 1: MVP
${formatList(prd.mvpScope, true)}

### Phase 2: Core Features
${formatList(prd.coreFeatures, true)}

### Phase 3: Future Enhancements
${formatList(prd.futureConsiderations, true)}

## Milestones

| Phase | Goal | Status |
|-------|------|--------|
| Phase 1 | MVP Launch | 🔄 In Progress |
| Phase 2 | Feature Complete | ⏳ Planned |
| Phase 3 | Enhancements | 📋 Backlog |

---
*Generated by Construct Architect*
`
}

/**
 * Generate SETUP markdown
 */
export function generateSETUP(plan: ArchitectPlan): string {
  const decisions = plan.decisions || {}

  return `# Development Setup

## Prerequisites

${getPrerequisites(decisions)}

## Environment Setup

### 1. Clone Repository

\`\`\`bash
git clone <repository-url>
cd ${toKebabCase(plan.name)}
\`\`\`

### 2. Install Dependencies

\`\`\`bash
${getInstallCommand(decisions)}
\`\`\`

### 3. Environment Variables

Create a \`.env\` file:

\`\`\`env
# App
APP_NAME=${plan.name}
NODE_ENV=development

# Database
DATABASE_URL=

# Auth
${getAuthEnvVars(decisions.auth)}
\`\`\`

### 4. Database Setup

\`\`\`bash
${getDatabaseSetupCommand(decisions)}
\`\`\`

### 5. Start Development

\`\`\`bash
${getDevCommand(decisions)}
\`\`\`

## IDE Setup

Recommended extensions:
${getIDEExtensions(decisions)}

## Troubleshooting

- **Port in use**: Check if another process is using the port
- **Database connection**: Verify DATABASE_URL is correct
- **Dependencies**: Try removing node_modules and reinstalling

---
*Generated by Construct Architect*
`
}

/**
 * Generate document by type
 */
export function generateDocument(type: DocumentType, plan: ArchitectPlan): string {
  switch (type) {
    case 'prd':
      return generatePRD(plan)
    case 'readme':
      return generateREADME(plan)
    case 'architecture':
      return generateARCHITECTURE(plan)
    case 'roadmap':
      return generateROADMAP(plan)
    case 'setup':
      return generateSETUP(plan)
    default:
      throw new Error(`Unknown document type: ${type}`)
  }
}

/**
 * Generate multiple documents
 */
export function generateDocuments(
  types: DocumentType[],
  plan: ArchitectPlan
): Record<DocumentType, string> {
  const docs: Partial<Record<DocumentType, string>> = {}
  for (const type of types) {
    docs[type] = generateDocument(type, plan)
  }
  return docs as Record<DocumentType, string>
}

/**
 * Get filename for document type
 */
export function getDocumentFilename(type: DocumentType, projectName?: string): string {
  if (projectName && projectName.trim()) {
    const title = getDocumentTitle(type, projectName)
    return `${toKebabCase(title)}.md`
  }

  switch (type) {
    case 'prd':
      return 'prd.md'
    case 'readme':
      return 'readme.md'
    case 'architecture':
      return 'architecture.md'
    case 'roadmap':
      return 'roadmap.md'
    case 'setup':
      return 'setup.md'
  }
}

/**
 * Get document title for type and project name.
 * This is shared by API document titles and local filename generation.
 */
export function getDocumentTitle(type: DocumentType, projectName: string): string {
  const name = projectName.trim() || 'Project'
  switch (type) {
    case 'prd':
      return name
    case 'readme':
      return `${name} - README`
    case 'architecture':
      return `${name} - Architecture`
    case 'roadmap':
      return `${name} - Roadmap`
    case 'setup':
      return `${name} - Setup`
  }
}

// Helper functions

function formatTechStack(decisions: ArchitectPlan['decisions']): string {
  const items: string[] = []
  if (decisions.platform) items.push(`- **Platform**: ${decisions.platform}`)
  if (decisions.frontend) items.push(`- **Frontend**: ${decisions.frontend}`)
  if (decisions.backend) items.push(`- **Backend**: ${decisions.backend}`)
  if (decisions.database) items.push(`- **Database**: ${decisions.database}`)
  if (decisions.auth?.length) items.push(`- **Auth**: ${Array.isArray(decisions.auth) ? decisions.auth.join(', ') : decisions.auth}`)
  if (decisions.styling) items.push(`- **Styling**: ${decisions.styling}`)
  if (decisions.hosting) items.push(`- **Hosting**: ${decisions.hosting}`)
  return items.length ? items.join('\n') : 'Not specified'
}

function formatList(items?: string | string[], asChecklist = false): string {
  if (!items?.length) return 'To be defined.'
  const arr = Array.isArray(items) ? items : [items]
  const prefix = asChecklist ? '- [ ] ' : '- '
  return arr.map(item => `${prefix}${item}`).join('\n')
}

function toKebabCase(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

function getPrerequisites(decisions: ArchitectPlan['decisions']): string {
  const prereqs: string[] = []
  const frontend = decisions.frontend?.toLowerCase() || ''
  const backend = decisions.backend?.toLowerCase() || ''

  if (frontend.includes('node') || frontend.includes('nuxt') || frontend.includes('next') || frontend.includes('react') || frontend.includes('vue')) {
    prereqs.push('- Node.js 18+ and npm/bun')
  }
  if (backend.includes('go') || backend.includes('gin')) {
    prereqs.push('- Go 1.21+')
  }
  if (backend.includes('python') || backend.includes('fastapi') || backend.includes('django')) {
    prereqs.push('- Python 3.11+')
  }
  if (decisions.database?.toLowerCase().includes('postgres')) {
    prereqs.push('- PostgreSQL 15+')
  }
  if (decisions.database?.toLowerCase().includes('mysql')) {
    prereqs.push('- MySQL 8+')
  }
  if (decisions.database?.toLowerCase().includes('mongo')) {
    prereqs.push('- MongoDB 6+')
  }

  return prereqs.length ? prereqs.join('\n') : '- Node.js 18+'
}

function getInstallCommand(decisions: ArchitectPlan['decisions']): string {
  const frontend = decisions.frontend?.toLowerCase() || ''
  if (frontend.includes('nuxt') || frontend.includes('vue')) return 'bun install'
  if (frontend.includes('next') || frontend.includes('react')) return 'npm install'
  return 'npm install'
}

function getDevCommand(decisions: ArchitectPlan['decisions']): string {
  const frontend = decisions.frontend?.toLowerCase() || ''
  if (frontend.includes('nuxt')) return 'bun run dev'
  if (frontend.includes('vue')) return 'bun run dev'
  if (frontend.includes('next')) return 'npm run dev'
  return 'npm run dev'
}

function getPlatformRationale(platform?: string): string {
  if (!platform) return ''
  const p = platform.toLowerCase()
  if (p.includes('web')) return 'Web platform chosen for broad accessibility and rapid deployment.'
  if (p.includes('mobile')) return 'Mobile-first approach for on-the-go user experience.'
  if (p.includes('desktop')) return 'Desktop application for enhanced performance and offline capabilities.'
  return ''
}

function getFrontendRationale(frontend?: string): string {
  if (!frontend) return ''
  const f = frontend.toLowerCase()
  if (f.includes('nuxt')) return 'Nuxt 3 provides SSR, auto-imports, and excellent Vue DX.'
  if (f.includes('next')) return 'Next.js offers React SSR with great performance optimization.'
  if (f.includes('react')) return 'React ecosystem provides flexibility and wide community support.'
  if (f.includes('vue')) return 'Vue offers gentle learning curve and great reactivity system.'
  return ''
}

function getBackendRationale(backend?: string): string {
  if (!backend) return ''
  const b = backend.toLowerCase()
  if (b.includes('go') || b.includes('gin')) return 'Go provides excellent performance and simple concurrency.'
  if (b.includes('node') || b.includes('express')) return 'Node.js allows JavaScript full-stack development.'
  if (b.includes('python') || b.includes('fastapi')) return 'Python offers rapid development and rich ecosystem.'
  return ''
}

function getDatabaseRationale(database?: string): string {
  if (!database) return ''
  const d = database.toLowerCase()
  if (d.includes('postgres')) return 'PostgreSQL provides robust ACID compliance and extensibility.'
  if (d.includes('mysql')) return 'MySQL offers proven reliability and wide hosting support.'
  if (d.includes('mongo')) return 'MongoDB provides flexible schema for evolving data models.'
  if (d.includes('sqlite')) return 'SQLite offers simplicity for embedded or small-scale applications.'
  return ''
}

function getAuthEnvVars(auth?: string | string[]): string {
  if (!auth?.length) return '# AUTH_SECRET='
  const authArray = Array.isArray(auth) ? auth : [auth]
  const vars: string[] = []
  for (const a of authArray) {
    const lower = a.toLowerCase()
    if (lower.includes('oauth') || lower.includes('google')) vars.push('GOOGLE_CLIENT_ID=\nGOOGLE_CLIENT_SECRET=')
    if (lower.includes('github')) vars.push('GITHUB_CLIENT_ID=\nGITHUB_CLIENT_SECRET=')
    if (lower.includes('jwt') || lower.includes('email')) vars.push('JWT_SECRET=')
  }
  return vars.length ? vars.join('\n') : 'AUTH_SECRET='
}

function getDatabaseSetupCommand(decisions: ArchitectPlan['decisions']): string {
  const db = decisions.database?.toLowerCase() || ''
  if (db.includes('postgres')) return '# Create database\ncreatedb myapp_dev\n\n# Run migrations\nnpm run db:migrate'
  if (db.includes('mysql')) return '# Create database\nmysql -e "CREATE DATABASE myapp_dev;"\n\n# Run migrations\nnpm run db:migrate'
  if (db.includes('sqlite')) return '# SQLite will create file automatically\nnpm run db:migrate'
  return '# Setup your database\nnpm run db:setup'
}

function getIDEExtensions(decisions: ArchitectPlan['decisions']): string {
  const exts: string[] = ['- ESLint', '- Prettier']
  const frontend = decisions.frontend?.toLowerCase() || ''
  const backend = decisions.backend?.toLowerCase() || ''

  if (frontend.includes('vue') || frontend.includes('nuxt')) exts.push('- Volar (Vue)')
  if (frontend.includes('react') || frontend.includes('next')) exts.push('- ES7+ React snippets')
  if (backend.includes('go')) exts.push('- Go')
  if (backend.includes('python')) exts.push('- Python', '- Pylance')

  return exts.join('\n')
}
