/**
 * Documents Generator
 * Generates project documentation from Architect plan.
 *
 * Supports two plan shapes:
 *   - Legacy: flat `prd` object at plan root
 *   - Rich (v2): `docs` object with prd, architecture, dataModels, uiSpec, roadmap, aiContext
 *
 * When the rich `docs` structure is present, generators produce deep, numbered
 * Frostline-style documents. Otherwise they fall back to the legacy generators.
 */

// ─── Types ──────────────────────────────────────────────────────────────────

export type DocumentType = 'prd' | 'readme' | 'architecture' | 'data-models' | 'ui-spec' | 'roadmap' | 'ai-context' | 'setup'

export interface RichPRD {
  overview?: string
  targetUsers?: string
  coreFeatures?: string[]
  userFlows?: string[]
  mvpScope?: string[]
  contentStructure?: string
  futureConsiderations?: string[]
}

export interface RichArchitecture {
  overview?: string
  systemDiagram?: string
  stateManagement?: string
  dataFlow?: string
  apiDesign?: string
  constraints?: string[]
  performanceTargets?: {
    initialLoad?: string
    interaction?: string
    build?: string
  }
  techRationale?: string
}

export interface RichDataModels {
  overview?: string
  entities?: Array<{
    name: string
    description?: string
    fields?: Array<{
      name: string
      type: string
      description?: string
      required?: boolean
      constraints?: string
    }>
    relationships?: string[]
  }>
  enums?: Array<{
    name: string
    values: string[]
    description?: string
  }>
  apiContracts?: Array<{
    endpoint: string
    request?: string
    response?: string
    description?: string
  }>
}

export interface RichUISpec {
  designSystem?: {
    colors?: Record<string, string>
    typography?: Record<string, string>
    spacing?: string
    borderRadius?: string
    shadows?: string
  }
  screens?: Array<{
    name: string
    layout?: string
    components?: string[]
    interactions?: string[]
    responsiveNotes?: string
  }>
  animations?: Array<{
    element: string
    trigger?: string
    effect?: string
    duration?: string
  }>
  responsiveBreakpoints?: Record<string, string>
}

export interface RichRoadmap {
  phases?: Array<{
    id: string
    name: string
    duration?: string
    goal?: string
    tasks?: string[]
    definitionOfDone?: string[]
  }>
}

export interface RichAIContext {
  projectStructure?: string
  conventions?: string[]
  patterns?: Array<{
    name: string
    steps: string[]
  }>
  commonMistakes?: Array<{
    mistake: string
    fix: string
  }>
  keyFiles?: Array<{
    path: string
    purpose: string
  }>
  testingStrategy?: string
}

export interface PlanDocs {
  prd?: RichPRD
  architecture?: RichArchitecture
  dataModels?: RichDataModels
  uiSpec?: RichUISpec
  roadmap?: RichRoadmap
  aiContext?: RichAIContext
}

export interface ArchitectPlan {
  name: string
  description: string
  type?: 'construct-space' | 'project'
  spaceId?: string
  spaceName?: string
  spaceScope?: 'project' | 'app' | 'both'
  spaceIcon?: string
  decisions: {
    platform?: string
    frontend?: string
    backend?: string
    database?: string
    auth?: string | string[]
    styling?: string
    hosting?: string
    spaces?: string[]
    [key: string]: string | string[] | undefined
  }
  techStack?: {
    framework?: string
    styling?: string
    animations?: string
    backend?: string
    database?: string
    hosting?: string
    key_libraries?: string[]
  }
  // Rich docs (v2) — generated by updated architect prompt
  docs?: PlanDocs
  // Legacy flat PRD — backward compat
  prd?: {
    overview?: string
    targetUsers?: string
    coreFeatures?: string[]
    techRationale?: string
    mvpScope?: string[]
    futureConsiderations?: string[]
    designNotes?: string
    sections?: string[]
    contentStructure?: string
  }
}

interface StackSnapshot {
  platform: string
  frontend: string
  backend: string
  database: string
  hosting: string
  styling: string
  animations: string
  libraries: string[]
  auth: string[]
}


export interface DocumentOption {
  type: DocumentType
  label: string
  description: string
  icon: string
  default: boolean
}

export const DOCUMENT_OPTIONS: DocumentOption[] = [
  {
    type: 'prd',
    label: 'Product Requirements',
    description: 'Detailed product requirements, user flows, and MVP scope',
    icon: 'i-lucide-file-text',
    default: true
  },
  {
    type: 'readme',
    label: 'README',
    description: 'Project overview, tech stack, and getting started',
    icon: 'i-lucide-book-open',
    default: true
  },
  {
    type: 'architecture',
    label: 'Architecture',
    description: 'System design, data flow, constraints, and tech rationale',
    icon: 'i-lucide-git-branch',
    default: true
  },
  {
    type: 'data-models',
    label: 'Data Models',
    description: 'Entity schemas, relationships, enums, and API contracts',
    icon: 'i-lucide-database',
    default: false
  },
  {
    type: 'ui-spec',
    label: 'UI Specification',
    description: 'Design system, screens, animations, and responsive rules',
    icon: 'i-lucide-palette',
    default: false
  },
  {
    type: 'roadmap',
    label: 'Roadmap',
    description: 'Phased delivery plan with tasks and definition of done',
    icon: 'i-lucide-map',
    default: true
  },
  {
    type: 'ai-context',
    label: 'AI Context',
    description: 'Agent guide: conventions, patterns, key files, common mistakes',
    icon: 'i-lucide-brain',
    default: true
  },
  {
    type: 'setup',
    label: 'Setup',
    description: 'Development environment setup instructions',
    icon: 'i-lucide-settings',
    default: false
  }
]

// ─── Helpers ────────────────────────────────────────────────────────────────

/** Check whether the plan has the rich v2 docs structure */
function hasRichDocs(plan: ArchitectPlan): boolean {
  return !!plan.docs && (!!plan.docs.prd || !!plan.docs.architecture || !!plan.docs.roadmap)
}

/** Get PRD data from whichever shape is available */
function getPRD(plan: ArchitectPlan): RichPRD & { techRationale?: string; designNotes?: string; sections?: string[] } {
  if (plan.docs?.prd) return plan.docs.prd as RichPRD & { techRationale?: string; designNotes?: string; sections?: string[] }
  return plan.prd || {}
}

// ─── Rich Document Generators (v2 — Frostline-style) ────────────────────────

function generateRichPRD(plan: ArchitectPlan): string {
  const prd = plan.docs!.prd || {}
  const stack = plan.techStack

  const sections: string[] = []
  sections.push(`# ${plan.name} — Product Requirements`)
  sections.push('')

  // Overview
  sections.push('## 1. Overview')
  sections.push(prd.overview || plan.description || 'No description provided.')
  sections.push('')

  // Target Users
  sections.push('## 2. Target Users')
  sections.push(prd.targetUsers || 'Define the primary audience, use cases, and user constraints.')
  sections.push('')

  // Tech Stack
  if (stack) {
    sections.push('## 3. Technology Stack')
    if (stack.framework) sections.push(`- **Framework**: ${stack.framework}`)
    if (stack.styling) sections.push(`- **Styling**: ${stack.styling}`)
    if (stack.animations) sections.push(`- **Animations**: ${stack.animations}`)
    if (stack.backend) sections.push(`- **Backend**: ${stack.backend}`)
    if (stack.database) sections.push(`- **Database**: ${stack.database}`)
    if (stack.hosting) sections.push(`- **Hosting**: ${stack.hosting}`)
    if (stack.key_libraries?.length) sections.push(`- **Key Libraries**: ${stack.key_libraries.join(', ')}`)
    sections.push('')
  }

  // Core Features
  sections.push(`## ${stack ? '4' : '3'}. Core Features`)
  if (prd.coreFeatures?.length) {
    for (const feature of prd.coreFeatures) {
      sections.push(`- ${feature}`)
    }
  } else {
    sections.push('To be defined.')
  }
  sections.push('')

  // User Flows
  if (prd.userFlows?.length) {
    sections.push('## 5. User Flows')
    for (let i = 0; i < prd.userFlows.length; i++) {
      sections.push(`${i + 1}. ${prd.userFlows[i]}`)
    }
    sections.push('')
  }

  // MVP Scope
  sections.push('## 6. MVP Scope')
  if (prd.mvpScope?.length) {
    for (const item of prd.mvpScope) {
      sections.push(`- [ ] ${item}`)
    }
  } else {
    sections.push('To be defined.')
  }
  sections.push('')

  // Content Structure
  if (prd.contentStructure) {
    sections.push('## 7. Content Structure')
    sections.push(prd.contentStructure)
    sections.push('')
  }

  // Future Considerations
  if (prd.futureConsiderations?.length) {
    sections.push('## 8. Future Considerations')
    for (const item of prd.futureConsiderations) {
      sections.push(`- ${item}`)
    }
    sections.push('')
  }

  sections.push('---')
  sections.push('*Generated by Construct Architect*')
  return sections.join('\n')
}

function generateRichArchitecture(plan: ArchitectPlan): string {
  const arch = plan.docs!.architecture || {}
  const sections: string[] = []

  sections.push(`# ${plan.name} — Technical Architecture`)
  sections.push('')

  sections.push('## 1. Overview')
  sections.push(arch.overview || `Technical architecture for ${plan.name}.`)
  sections.push('')

  if (arch.systemDiagram) {
    sections.push('## 2. System Diagram')
    sections.push('```')
    sections.push(arch.systemDiagram)
    sections.push('```')
    sections.push('')
  }

  if (arch.stateManagement) {
    sections.push('## 3. State Management')
    sections.push(arch.stateManagement)
    sections.push('')
  }

  if (arch.dataFlow) {
    sections.push('## 4. Data Flow')
    sections.push(arch.dataFlow)
    sections.push('')
  }

  if (arch.apiDesign) {
    sections.push('## 5. API Design')
    sections.push(arch.apiDesign)
    sections.push('')
  }

  if (arch.constraints?.length) {
    sections.push('## 6. Constraints')
    for (const c of arch.constraints) {
      sections.push(`- ${c}`)
    }
    sections.push('')
  }

  if (arch.performanceTargets) {
    sections.push('## 7. Performance Targets')
    const pt = arch.performanceTargets
    if (pt.initialLoad) sections.push(`- **Initial Load**: ${pt.initialLoad}`)
    if (pt.interaction) sections.push(`- **Interaction**: ${pt.interaction}`)
    if (pt.build) sections.push(`- **Build**: ${pt.build}`)
    sections.push('')
  }

  if (arch.techRationale) {
    sections.push('## 8. Technical Rationale')
    sections.push(arch.techRationale)
    sections.push('')
  }

  sections.push('---')
  sections.push('*Generated by Construct Architect*')
  return sections.join('\n')
}

function generateRichDataModels(plan: ArchitectPlan): string {
  const dm = plan.docs!.dataModels || {}
  const sections: string[] = []

  sections.push(`# ${plan.name} — Data Models & Schemas`)
  sections.push('')

  sections.push('## 1. Overview')
  sections.push(dm.overview || 'Data architecture for this project.')
  sections.push('')

  if (dm.entities?.length) {
    sections.push('## 2. Entities')
    sections.push('')
    for (const entity of dm.entities) {
      sections.push(`### ${entity.name}`)
      if (entity.description) sections.push(entity.description)
      sections.push('')

      if (entity.fields?.length) {
        sections.push('| Field | Type | Required | Description | Constraints |')
        sections.push('|-------|------|----------|-------------|-------------|')
        for (const f of entity.fields) {
          sections.push(`| ${f.name} | ${f.type} | ${f.required ? 'Yes' : 'No'} | ${f.description || ''} | ${f.constraints || ''} |`)
        }
        sections.push('')
      }

      if (entity.relationships?.length) {
        sections.push('**Relationships:**')
        for (const r of entity.relationships) {
          sections.push(`- ${r}`)
        }
        sections.push('')
      }
    }
  }

  if (dm.enums?.length) {
    sections.push('## 3. Enums')
    sections.push('')
    for (const e of dm.enums) {
      sections.push(`### ${e.name}`)
      if (e.description) sections.push(e.description)
      sections.push(`\nValues: \`${e.values.join('` | `')}\``)
      sections.push('')
    }
  }

  if (dm.apiContracts?.length) {
    sections.push('## 4. API Contracts')
    sections.push('')
    for (const api of dm.apiContracts) {
      sections.push(`### \`${api.endpoint}\``)
      if (api.description) sections.push(api.description)
      if (api.request) sections.push(`\n**Request:** \`${api.request}\``)
      if (api.response) sections.push(`**Response:** \`${api.response}\``)
      sections.push('')
    }
  }

  sections.push('---')
  sections.push('*Generated by Construct Architect*')
  return sections.join('\n')
}

function generateRichUISpec(plan: ArchitectPlan): string {
  const ui = plan.docs!.uiSpec || {}
  const sections: string[] = []

  sections.push(`# ${plan.name} — UI/UX Specification`)
  sections.push('')

  if (ui.designSystem) {
    sections.push('## 1. Design System')
    sections.push('')

    if (ui.designSystem.colors) {
      sections.push('### Colors')
      for (const [name, value] of Object.entries(ui.designSystem.colors)) {
        sections.push(`- **${name}**: ${value}`)
      }
      sections.push('')
    }

    if (ui.designSystem.typography) {
      sections.push('### Typography')
      for (const [name, value] of Object.entries(ui.designSystem.typography)) {
        sections.push(`- **${name}**: ${value}`)
      }
      sections.push('')
    }

    if (ui.designSystem.spacing) {
      sections.push('### Spacing')
      sections.push(ui.designSystem.spacing)
      sections.push('')
    }

    if (ui.designSystem.borderRadius) {
      sections.push('### Border Radius')
      sections.push(ui.designSystem.borderRadius)
      sections.push('')
    }

    if (ui.designSystem.shadows) {
      sections.push('### Shadows')
      sections.push(ui.designSystem.shadows)
      sections.push('')
    }
  }

  if (ui.screens?.length) {
    sections.push('## 2. Screens')
    sections.push('')
    for (const screen of ui.screens) {
      sections.push(`### ${screen.name}`)

      if (screen.layout) {
        sections.push('```')
        sections.push(screen.layout)
        sections.push('```')
      }

      if (screen.components?.length) {
        sections.push('\n**Components:**')
        for (const c of screen.components) sections.push(`- ${c}`)
      }

      if (screen.interactions?.length) {
        sections.push('\n**Interactions:**')
        for (const i of screen.interactions) sections.push(`- ${i}`)
      }

      if (screen.responsiveNotes) {
        sections.push(`\n**Responsive:** ${screen.responsiveNotes}`)
      }
      sections.push('')
    }
  }

  if (ui.animations?.length) {
    sections.push('## 3. Animations')
    sections.push('')
    sections.push('| Element | Trigger | Effect | Duration |')
    sections.push('|---------|---------|--------|----------|')
    for (const a of ui.animations) {
      sections.push(`| ${a.element} | ${a.trigger || ''} | ${a.effect || ''} | ${a.duration || ''} |`)
    }
    sections.push('')
  }

  if (ui.responsiveBreakpoints) {
    sections.push('## 4. Responsive Breakpoints')
    for (const [name, value] of Object.entries(ui.responsiveBreakpoints)) {
      sections.push(`- **${name}**: ${value}`)
    }
    sections.push('')
  }

  sections.push('---')
  sections.push('*Generated by Construct Architect*')
  return sections.join('\n')
}

function generateRichRoadmap(plan: ArchitectPlan): string {
  const rm = plan.docs!.roadmap || {}
  const sections: string[] = []

  sections.push(`# ${plan.name} — Development Roadmap`)
  sections.push('')

  if (rm.phases?.length) {
    for (const phase of rm.phases) {
      sections.push(`## ${phase.name}${phase.duration ? ` (${phase.duration})` : ''}`)
      if (phase.goal) sections.push(`\n**Goal:** ${phase.goal}`)
      sections.push('')

      if (phase.tasks?.length) {
        sections.push('### Tasks')
        for (const task of phase.tasks) {
          sections.push(`- [ ] ${task}`)
        }
        sections.push('')
      }

      if (phase.definitionOfDone?.length) {
        sections.push('### Definition of Done')
        for (const d of phase.definitionOfDone) {
          sections.push(`- [ ] ${d}`)
        }
        sections.push('')
      }
    }
  } else {
    sections.push('Roadmap phases to be defined.')
    sections.push('')
  }

  sections.push('---')
  sections.push('*Generated by Construct Architect*')
  return sections.join('\n')
}

function generateRichAIContext(plan: ArchitectPlan): string {
  const ai = plan.docs!.aiContext || {}
  const sections: string[] = []

  sections.push(`# ${plan.name} — AI Agent Context Guide`)
  sections.push('')
  sections.push('> This document tells code agents HOW to work in this project.')
  sections.push('> Patterns, conventions, and common mistakes to avoid.')
  sections.push('')

  if (ai.projectStructure) {
    sections.push('## 1. Project Structure')
    sections.push('```')
    sections.push(ai.projectStructure)
    sections.push('```')
    sections.push('')
  }

  if (ai.conventions?.length) {
    sections.push('## 2. Conventions')
    for (const c of ai.conventions) {
      sections.push(`- ${c}`)
    }
    sections.push('')
  }

  if (ai.patterns?.length) {
    sections.push('## 3. Common Patterns')
    sections.push('')
    for (const p of ai.patterns) {
      sections.push(`### ${p.name}`)
      for (const step of p.steps) {
        sections.push(`${step}`)
      }
      sections.push('')
    }
  }

  if (ai.commonMistakes?.length) {
    sections.push('## 4. Common Mistakes')
    sections.push('')
    for (const m of ai.commonMistakes) {
      sections.push(`- **Mistake:** ${m.mistake}`)
      sections.push(`  **Fix:** ${m.fix}`)
    }
    sections.push('')
  }

  if (ai.keyFiles?.length) {
    sections.push('## 5. Key Files')
    sections.push('')
    sections.push('| Path | Purpose |')
    sections.push('|------|---------|')
    for (const f of ai.keyFiles) {
      sections.push(`| \`${f.path}\` | ${f.purpose} |`)
    }
    sections.push('')
  }

  if (ai.testingStrategy) {
    sections.push('## 6. Testing Strategy')
    sections.push(ai.testingStrategy)
    sections.push('')
  }

  sections.push('---')
  sections.push('*Generated by Construct Architect*')
  return sections.join('\n')
}

// ─── Legacy Document Generators ─────────────────────────────────────────────

function generateLegacyPRD(plan: ArchitectPlan): string {
  const prd = plan.prd || {}
  const stack = getStackSnapshot(plan)

  return `# ${plan.name} PRD

## Product Summary
${prd.overview || plan.description || 'No description provided.'}

## Target Users
${prd.targetUsers || 'Define the primary audience, use cases, and user constraints.'}

## Product Shape
${formatDecisionHighlights(plan, stack)}

## Core Features
${formatList(prd.coreFeatures)}

## MVP Release Definition
${formatList(prd.mvpScope, true)}

## Technical Direction
${formatStackNarrative(plan, stack)}

## Technical Rationale
${prd.techRationale || 'Capture why this stack and architecture fit the initial release.'}

## Design Direction
${prd.designNotes || 'Document visual identity, motion, typography, and layout principles.'}
${prd.sections?.length ? `\n## Primary Screens / Sections\n${prd.sections.map((s, i) => `${i + 1}. ${s}`).join('\n')}` : ''}
${prd.contentStructure ? `\n## Content Structure\n${prd.contentStructure}` : ''}

## Future Considerations
${formatList(prd.futureConsiderations)}

---
*Generated by Construct Architect*
`
}

function generateLegacyArchitecture(plan: ArchitectPlan): string {
  const decisions = plan.decisions || {}
  const prd = plan.prd || {}
  const stack = getStackSnapshot(plan)
  const frontend = firstNonEmpty(decisions.frontend as string, stack.frontend)
  const backend = firstNonEmpty(decisions.backend as string, stack.backend)
  const database = firstNonEmpty(decisions.database as string, stack.database)
  const auth = stack.auth.length > 0
    ? stack.auth
    : normalizeStringArray(decisions.auth)

  return `# Architecture

## Overview
This document outlines the technical architecture for ${plan.name}.

## Technology Choices

### Frontend: ${frontend || 'Not specified'}
### Backend: ${backend || 'Not specified'}
### Database: ${database || 'Not specified'}

### Authentication
${formatList(auth)}

## Technical Rationale
${prd.techRationale || 'The technology choices were made based on project requirements, team expertise, and scalability needs.'}

## System Diagram

\`\`\`
┌─────────────┐     ┌─────────────┐     ┌─────────────┐
│   Client    │────▶│   Server    │────▶│  Database   │
│ ${(frontend || 'Frontend').padEnd(11)}│     │ ${(backend || 'Backend').padEnd(11)}│     │ ${(database || 'DB').padEnd(11)}│
└─────────────┘     └─────────────┘     └─────────────┘
\`\`\`

---
*Generated by Construct Architect*
`
}

function generateLegacyRoadmap(plan: ArchitectPlan): string {
  const prd = plan.prd || {}

  return `# Roadmap

## ${plan.name}

### Phase 1: MVP
${formatList(prd.mvpScope, true)}

### Phase 2: Core Features
${formatList(prd.coreFeatures, true)}

### Phase 3: Future Enhancements
${formatList(prd.futureConsiderations, true)}

---
*Generated by Construct Architect*
`
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Generate PRD markdown
 */
export function generatePRD(plan: ArchitectPlan): string {
  if (hasRichDocs(plan) && plan.docs?.prd) return generateRichPRD(plan)
  return generateLegacyPRD(plan)
}

/**
 * Generate README markdown
 */
export function generateREADME(plan: ArchitectPlan): string {
  const prd = getPRD(plan)
  const stack = getStackSnapshot(plan)

  return `# ${plan.name}

${prd.overview || plan.description || ''}

## Tech Stack

${formatTechStackFromSnapshot(stack)}

${stack.libraries.length ? `## Key Libraries\n\n${stack.libraries.map(lib => `- ${lib}`).join('\n')}\n` : ''}## Getting Started

### Prerequisites

${getPrerequisites(plan)}

### Installation

\`\`\`bash
# Clone the repository
git clone <repository-url>
cd ${toKebabCase(plan.name)}

${getInstallCommand(plan)}
\`\`\`

### Run Locally

\`\`\`bash
${getDevCommand(plan)}
\`\`\`

## Documentation

Project documentation lives in \`docs/\`.

${getDocumentIndex(plan)}

---
*Generated by Construct Architect*
`
}

/**
 * Generate ARCHITECTURE markdown
 */
export function generateARCHITECTURE(plan: ArchitectPlan): string {
  if (hasRichDocs(plan) && plan.docs?.architecture) return generateRichArchitecture(plan)
  return generateLegacyArchitecture(plan)
}

/**
 * Generate DATA MODELS markdown
 */
export function generateDataModels(plan: ArchitectPlan): string {
  if (hasRichDocs(plan) && plan.docs?.dataModels) return generateRichDataModels(plan)
  // No legacy equivalent — produce a stub
  return `# ${plan.name} — Data Models

Data model schemas to be defined.

---
*Generated by Construct Architect*
`
}

/**
 * Generate UI SPEC markdown
 */
export function generateUISpec(plan: ArchitectPlan): string {
  if (hasRichDocs(plan) && plan.docs?.uiSpec) return generateRichUISpec(plan)
  return `# ${plan.name} — UI Specification

UI specification to be defined.

---
*Generated by Construct Architect*
`
}

/**
 * Generate ROADMAP markdown
 */
export function generateROADMAP(plan: ArchitectPlan): string {
  if (hasRichDocs(plan) && plan.docs?.roadmap) return generateRichRoadmap(plan)
  return generateLegacyRoadmap(plan)
}

/**
 * Generate AI CONTEXT markdown
 */
export function generateAIContext(plan: ArchitectPlan): string {
  if (hasRichDocs(plan) && plan.docs?.aiContext) return generateRichAIContext(plan)
  return `# ${plan.name} — AI Agent Context Guide

AI context guide to be defined.

---
*Generated by Construct Architect*
`
}

/**
 * Generate SETUP markdown
 */
export function generateSETUP(plan: ArchitectPlan): string {
  const stack = getStackSnapshot(plan)

  return `# Development Setup

## Prerequisites

${getPrerequisites(plan)}

## Environment Setup

### 1. Clone Repository

\`\`\`bash
git clone <repository-url>
cd ${toKebabCase(plan.name)}
\`\`\`

### 2. Install Dependencies

\`\`\`bash
${getInstallCommand(plan)}
\`\`\`

### 3. Environment Variables

Create a \`.env\` file:

\`\`\`env
# App
APP_NAME=${plan.name}
NODE_ENV=development

# Database
DATABASE_URL=

# Auth
${getAuthEnvVars(stack.auth)}
\`\`\`

### 4. Database Setup

\`\`\`bash
${getDatabaseSetupCommandForStack(stack)}
\`\`\`

### 5. Start Development

\`\`\`bash
${getDevCommand(plan)}
\`\`\`

## IDE Setup

Recommended extensions:
${getIDEExtensionsForStack(stack)}

---
*Generated by Construct Architect*
`
}

/**
 * Generate document by type
 */
export function generateDocument(type: DocumentType, plan: ArchitectPlan): string {
  switch (type) {
    case 'prd':
      return generatePRD(plan)
    case 'readme':
      return generateREADME(plan)
    case 'architecture':
      return generateARCHITECTURE(plan)
    case 'data-models':
      return generateDataModels(plan)
    case 'ui-spec':
      return generateUISpec(plan)
    case 'roadmap':
      return generateROADMAP(plan)
    case 'ai-context':
      return generateAIContext(plan)
    case 'setup':
      return generateSETUP(plan)
    default:
      throw new Error(`Unknown document type: ${type}`)
  }
}

/**
 * Generate multiple documents
 */
export function generateDocuments(
  types: DocumentType[],
  plan: ArchitectPlan
): Record<string, string> {
  const docs: Record<string, string> = {}
  for (const type of types) {
    docs[type] = generateDocument(type, plan)
  }
  return docs
}

/**
 * Get filename for document type — numbered for rich docs
 */
export function getDocumentFilename(type: DocumentType, projectName?: string): string {
  switch (type) {
    case 'prd':
      return '01-product-requirements.md'
    case 'readme':
      return 'README.md'
    case 'architecture':
      return '02-technical-architecture.md'
    case 'data-models':
      return '03-data-models.md'
    case 'ui-spec':
      return '04-ui-specification.md'
    case 'roadmap':
      return '05-development-roadmap.md'
    case 'ai-context':
      return '06-ai-context.md'
    case 'setup':
      return '07-setup.md'
  }
}

/**
 * Get document title for type and project name.
 */
export function getDocumentTitle(type: DocumentType, projectName: string): string {
  const name = projectName.trim() || 'Project'
  switch (type) {
    case 'prd':
      return `${name} — Product Requirements`
    case 'readme':
      return `${name} — README`
    case 'architecture':
      return `${name} — Technical Architecture`
    case 'data-models':
      return `${name} — Data Models`
    case 'ui-spec':
      return `${name} — UI Specification`
    case 'roadmap':
      return `${name} — Development Roadmap`
    case 'ai-context':
      return `${name} — AI Context Guide`
    case 'setup':
      return `${name} — Setup`
  }
}

// ─── Internal helpers ───────────────────────────────────────────────────────

function getDocumentIndex(plan: ArchitectPlan): string {
  if (hasRichDocs(plan)) {
    const lines = [
      '- `docs/01-product-requirements.md` — product requirements and scope',
      '- `docs/02-technical-architecture.md` — system design and constraints',
    ]
    if (plan.docs?.dataModels) lines.push('- `docs/03-data-models.md` — entity schemas and API contracts')
    if (plan.docs?.uiSpec) lines.push('- `docs/04-ui-specification.md` — design system and screens')
    lines.push('- `docs/05-development-roadmap.md` — phased delivery plan')
    lines.push('- `docs/06-ai-context.md` — agent guide and conventions')
    return lines.join('\n')
  }
  return `- \`docs/01-product-requirements.md\` — product requirements and scope
- \`docs/02-technical-architecture.md\` — system design`
}

function getStackSnapshot(plan: ArchitectPlan): StackSnapshot {
  const decisions = plan.decisions || {}
  const techStack = plan.techStack || {}
  const projectText = getPlanNarrativeText(plan)

  return {
    platform: firstNonEmpty(decisions.platform as string, inferPlatformFromText(projectText)),
    frontend: firstNonEmpty(decisions.frontend as string, techStack.framework, inferFrontendFromText(projectText)),
    backend: firstNonEmpty(decisions.backend as string, techStack.backend, inferBackendFromText(projectText)),
    database: firstNonEmpty(decisions.database as string, techStack.database, inferDatabaseFromText(projectText)),
    hosting: firstNonEmpty(decisions.hosting as string, techStack.hosting, inferHostingFromText(projectText)),
    styling: firstNonEmpty(decisions.styling as string, techStack.styling),
    animations: firstNonEmpty(techStack.animations, inferAnimationApproachFromText(projectText)),
    libraries: uniqueValues([...(techStack.key_libraries || []), ...inferLibrariesFromText(projectText)]),
    auth: normalizeStringArray(decisions.auth),
  }
}

function formatTechStackFromSnapshot(stack: StackSnapshot): string {
  const items: string[] = []
  if (stack.platform) items.push(`- **Platform**: ${stack.platform}`)
  if (stack.frontend) items.push(`- **Frontend**: ${stack.frontend}`)
  if (stack.backend) items.push(`- **Backend**: ${stack.backend}`)
  if (stack.database) items.push(`- **Database**: ${stack.database}`)
  if (stack.styling) items.push(`- **Styling**: ${stack.styling}`)
  if (stack.animations) items.push(`- **Animations**: ${stack.animations}`)
  if (stack.hosting) items.push(`- **Hosting**: ${stack.hosting}`)
  return items.length ? items.join('\n') : 'Not specified'
}

function formatDecisionHighlights(plan: ArchitectPlan, stack: StackSnapshot): string {
  const highlights: string[] = []
  if (stack.platform) highlights.push(`- **Platform**: ${stack.platform}`)
  if (stack.frontend) highlights.push(`- **Frontend**: ${stack.frontend}`)
  if (stack.backend) highlights.push(`- **Backend**: ${stack.backend}`)
  if (stack.database) highlights.push(`- **Database**: ${stack.database}`)
  if (stack.auth.length > 0) highlights.push(`- **Authentication**: ${stack.auth.join(', ')}`)
  if (stack.hosting) highlights.push(`- **Hosting**: ${stack.hosting}`)
  const spaces = Array.isArray(plan.decisions?.spaces) ? plan.decisions.spaces : []
  if (spaces.length > 0) highlights.push(`- **Construct Spaces**: ${spaces.join(', ')}`)
  return highlights.length ? highlights.join('\n') : '- Product direction still needs to be defined.'
}

function formatStackNarrative(plan: ArchitectPlan, stack: StackSnapshot): string {
  const parts: string[] = []
  if (plan.techStack?.framework) parts.push(`**Framework:** ${plan.techStack.framework}`)
  if (plan.techStack?.backend) parts.push(`**Backend:** ${plan.techStack.backend}`)
  if (plan.techStack?.database) parts.push(`**Database:** ${plan.techStack.database}`)
  if (plan.techStack?.styling) parts.push(`**Styling:** ${plan.techStack.styling}`)
  if (plan.techStack?.animations) parts.push(`**Animations:** ${plan.techStack.animations}`)
  if (plan.techStack?.hosting) parts.push(`**Hosting:** ${plan.techStack.hosting}`)
  if (plan.techStack?.key_libraries?.length) parts.push(`**Key libraries:** ${plan.techStack.key_libraries.join(', ')}`)

  if (parts.length > 0) return parts.join('\n\n')

  const targets: string[] = []
  if (stack.frontend) targets.push(`- **Primary client**: ${stack.frontend}`)
  if (stack.backend) targets.push(`- **Backend/API**: ${stack.backend}`)
  if (stack.hosting) targets.push(`- **Deployment**: ${stack.hosting}`)
  return targets.length > 0 ? targets.join('\n') : `- **Primary goal**: ${plan.description || 'To be defined.'}`
}

function formatList(items?: string | string[], asChecklist = false): string {
  if (!items?.length) return 'To be defined.'
  const arr = Array.isArray(items) ? items : [items]
  const prefix = asChecklist ? '- [ ] ' : '- '
  return arr.map(item => `${prefix}${item}`).join('\n')
}

function firstNonEmpty(...values: Array<string | undefined>): string {
  for (const value of values) {
    if (typeof value === 'string' && value.trim()) return value.trim()
  }
  return ''
}

function getPlanNarrativeText(plan: ArchitectPlan): string {
  const prd = plan.prd || plan.docs?.prd || {}
  const decisionValues = Object.values(plan.decisions || {}).flatMap(value => normalizeStringArray(value))
  const techValues = normalizeStringArray([
    plan.techStack?.framework,
    plan.techStack?.styling,
    plan.techStack?.animations,
    plan.techStack?.backend,
    plan.techStack?.database,
    plan.techStack?.hosting,
    ...(plan.techStack?.key_libraries || []),
  ])

  return [
    plan.name,
    plan.description,
    (prd as Record<string, unknown>).overview as string,
    (prd as Record<string, unknown>).targetUsers as string,
    ...normalizeStringArray((prd as Record<string, unknown>).coreFeatures as string[]),
    ...normalizeStringArray((prd as Record<string, unknown>).mvpScope as string[]),
    ...normalizeStringArray((prd as Record<string, unknown>).futureConsiderations as string[]),
    ...decisionValues,
    ...techValues,
  ]
    .filter(Boolean)
    .join(' ')
}

function normalizeStringArray(value?: string | string[] | Array<string | undefined> | unknown): string[] {
  if (!value) return []
  const items = Array.isArray(value) ? value : [value]
  return items
    .flatMap(item => typeof item === 'string' ? [item] : [])
    .map(item => item.trim())
    .filter(Boolean)
}

function uniqueValues(items: string[]): string[] {
  return Array.from(new Set(items.map(item => item.trim()).filter(Boolean)))
}

function toKebabCase(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

// ─── Inference helpers ──────────────────────────────────────────────────────

function inferPlatformFromText(text: string): string {
  return inferNamedChoice(text, [
    [/\bflutter\b|\breact[\s-]?native\b|\bexpo\b|\bios\b|\bandroid\b|\bmobile\b/i, 'Mobile'],
    [/\btauri\b|\belectron\b|\bdesktop\b/i, 'Desktop'],
    [/\bnext(?:\.js)?\b|\bnuxt\b|\breact\b|\bvue\b|\bastro\b|\bweb\b|\bwebsite\b|\blanding page\b|\bsaas\b|\bdashboard\b/i, 'Web'],
  ])
}

function inferFrontendFromText(text: string): string {
  if (/\bflutter\b/i.test(text)) {
    return /\bgetx\b/i.test(text) ? 'Flutter (GetX)' : 'Flutter'
  }
  return inferNamedChoice(text, [
    [/\bexpo\b/i, 'Expo'],
    [/\breact[\s-]?native\b/i, 'React Native'],
    [/\bnext(?:\.js)?\b/i, 'Next.js'],
    [/\bnuxt\b/i, 'Nuxt'],
    [/\bvue\b/i, 'Vue'],
    [/\breact\b/i, 'React'],
    [/\btauri\b/i, 'Tauri'],
  ])
}

function inferBackendFromText(text: string): string {
  return inferNamedChoice(text, [
    [/\bgin\b|\bfiber\b|\becho\b|\bchi\b|\bgolang\b|\bgo backend\b|\bgo api\b|\bgo\b/i, 'Go'],
    [/\bfastapi\b/i, 'FastAPI'],
    [/\bexpress(?:\.js)?\b|\bnode(?:\.js)?\b/i, 'Node.js / Express'],
    [/\bnest(?:\.js)?\b/i, 'NestJS'],
    [/\bdjango\b/i, 'Django'],
    [/\blaravel\b/i, 'Laravel'],
    [/\brails\b/i, 'Rails'],
  ])
}

function inferDatabaseFromText(text: string): string {
  return inferNamedChoice(text, [
    [/\bsupabase\b/i, 'Supabase / PostgreSQL'],
    [/\bpostgres(?:ql)?\b/i, 'PostgreSQL'],
    [/\bsqlite\b/i, 'SQLite'],
    [/\bmysql\b/i, 'MySQL'],
    [/\bmongo(?:db)?\b/i, 'MongoDB'],
    [/\bfirebase\b/i, 'Firebase'],
  ])
}

function inferHostingFromText(text: string): string {
  return inferNamedChoice(text, [
    [/\bvercel\b/i, 'Vercel'],
    [/\bnetlify\b/i, 'Netlify'],
    [/\bfly\.io\b|\bfly io\b/i, 'Fly.io'],
    [/\brender\b/i, 'Render'],
    [/\brailway\b/i, 'Railway'],
    [/\baws\b/i, 'AWS'],
    [/\bcloudflare\b/i, 'Cloudflare'],
    [/\bfirebase\b/i, 'Firebase'],
    [/\bapp store\b|\bplay store\b/i, 'App Store / Play Store'],
  ])
}

function inferAnimationApproachFromText(text: string): string {
  return inferNamedChoice(text, [
    [/\breal[-\s]?time chat\b|\breal[-\s]?time\b|\blive updates?\b/i, 'Realtime updates and event-driven UI feedback'],
    [/\benergetic\b|\bsporty\b|\bplayful\b|\bbouncy\b/i, 'Snappy motion with spring-based transitions'],
    [/\bsubtle\b|\bminimal\b/i, 'Subtle motion and micro-interactions'],
  ])
}

function inferLibrariesFromText(text: string): string[] {
  const inferred: string[] = []
  if (/\bgetx\b/i.test(text)) inferred.push('GetX')
  if (/\briverpod\b/i.test(text)) inferred.push('Riverpod')
  if (/\bbloc\b/i.test(text)) inferred.push('flutter_bloc')
  if (/\bdio\b/i.test(text)) inferred.push('Dio')
  if (/\bsupabase\b/i.test(text)) inferred.push('Supabase')
  if (/\bfirebase\b/i.test(text)) inferred.push('Firebase')
  if (/\bmapbox\b/i.test(text)) inferred.push('Mapbox')
  if (/\bgoogle maps?\b/i.test(text)) inferred.push('Google Maps')
  if (/\breal[-\s]?time chat\b|\bwebsocket\b/i.test(text)) inferred.push('WebSocket transport')
  return inferred
}

function inferNamedChoice(text: string, patterns: Array<[RegExp, string]>): string {
  for (const [pattern, label] of patterns) {
    if (pattern.test(text)) return label
  }
  return ''
}

function getPrerequisites(plan: ArchitectPlan): string {
  const stack = getStackSnapshot(plan)
  const prereqs: string[] = []
  const frontend = `${stack.frontend} ${stack.platform}`.toLowerCase()
  const backend = stack.backend.toLowerCase()

  if (frontend.includes('node') || frontend.includes('nuxt') || frontend.includes('next') || frontend.includes('react') || frontend.includes('vue')) {
    prereqs.push('- Node.js 18+ and npm/bun')
  }
  if (frontend.includes('flutter')) {
    prereqs.push('- Flutter SDK 3.24+')
    prereqs.push('- Dart SDK (bundled with Flutter)')
  }
  if (frontend.includes('react native')) {
    prereqs.push('- Node.js 18+ and npm/yarn')
    prereqs.push('- React Native Android/iOS toolchain')
  }
  if (backend.includes('go') || backend.includes('gin')) {
    prereqs.push('- Go 1.21+')
  }
  if (backend.includes('python') || backend.includes('fastapi') || backend.includes('django')) {
    prereqs.push('- Python 3.11+')
  }
  if (stack.database.toLowerCase().includes('postgres')) {
    prereqs.push('- PostgreSQL 15+')
  }
  if (stack.database.toLowerCase().includes('mysql')) {
    prereqs.push('- MySQL 8+')
  }
  if (stack.database.toLowerCase().includes('mongo')) {
    prereqs.push('- MongoDB 6+')
  }

  return prereqs.length ? prereqs.join('\n') : '- Node.js 18+'
}

function getInstallCommand(plan: ArchitectPlan): string {
  const stack = getStackSnapshot(plan)
  const frontend = `${stack.frontend} ${stack.platform}`.toLowerCase()
  const backend = stack.backend.toLowerCase()
  const commands: string[] = []

  if (frontend.includes('flutter')) {
    commands.push('flutter pub get')
  } else if (frontend.includes('nuxt') || frontend.includes('vue')) {
    commands.push('bun install')
  } else if (frontend.includes('next') || frontend.includes('react native') || frontend.includes('react')) {
    commands.push('npm install')
  }

  if (backend.includes('go')) {
    if (commands.length) commands.push('')
    commands.push('# Backend')
    commands.push('go mod tidy')
  } else if (backend.includes('node') || backend.includes('express')) {
    if (commands.length) commands.push('')
    commands.push('# Backend')
    commands.push('npm install')
  }

  return commands.join('\n') || 'npm install'
}

function getDevCommand(plan: ArchitectPlan): string {
  const stack = getStackSnapshot(plan)
  const frontend = `${stack.frontend} ${stack.platform}`.toLowerCase()
  const backend = stack.backend.toLowerCase()
  const commands: string[] = []

  if (frontend.includes('flutter')) {
    commands.push('flutter run')
  } else if (frontend.includes('nuxt') || frontend.includes('vue')) {
    commands.push('bun run dev')
  } else if (frontend.includes('next') || frontend.includes('react native') || frontend.includes('react')) {
    commands.push('npm run dev')
  }

  if (backend.includes('go')) {
    if (commands.length) commands.push('')
    commands.push('# API')
    commands.push('go run ./cmd/api')
  } else if (backend.includes('node') || backend.includes('express')) {
    if (commands.length) commands.push('')
    commands.push('# API')
    commands.push('npm run api:dev')
  }

  return commands.join('\n') || 'npm run dev'
}

function getAuthEnvVars(auth?: string | string[]): string {
  if (!auth?.length) return '# AUTH_SECRET='
  const authArray = Array.isArray(auth) ? auth : [auth]
  const vars: string[] = []
  for (const a of authArray) {
    const lower = a.toLowerCase()
    if (lower.includes('oauth') || lower.includes('google')) vars.push('GOOGLE_CLIENT_ID=\nGOOGLE_CLIENT_SECRET=')
    if (lower.includes('github')) vars.push('GITHUB_CLIENT_ID=\nGITHUB_CLIENT_SECRET=')
    if (lower.includes('jwt') || lower.includes('email')) vars.push('JWT_SECRET=')
  }
  return vars.length ? vars.join('\n') : 'AUTH_SECRET='
}

function getDatabaseSetupCommandForStack(stack: StackSnapshot): string {
  const db = stack.database.toLowerCase()
  const backend = stack.backend.toLowerCase()
  const migrateCommand = backend.includes('go') ? 'go run ./cmd/migrate' : 'npm run db:migrate'
  if (db.includes('postgres')) return `# Create database\ncreatedb myapp_dev\n\n# Run migrations\n${migrateCommand}`
  if (db.includes('mysql')) return `# Create database\nmysql -e "CREATE DATABASE myapp_dev;"\n\n# Run migrations\n${migrateCommand}`
  if (db.includes('sqlite')) return `# SQLite will create file automatically\n${migrateCommand}`
  return '# Setup your database\nnpm run db:setup'
}

function getIDEExtensionsForStack(stack: StackSnapshot): string {
  const exts: string[] = ['- ESLint', '- Prettier']
  const frontend = stack.frontend.toLowerCase()
  const backend = stack.backend.toLowerCase()

  if (frontend.includes('flutter')) exts.push('- Dart', '- Flutter')
  if (frontend.includes('vue') || frontend.includes('nuxt')) exts.push('- Volar (Vue)')
  if (frontend.includes('react') || frontend.includes('next')) exts.push('- ES7+ React snippets')
  if (backend.includes('go')) exts.push('- Go')
  if (backend.includes('python')) exts.push('- Python', '- Pylance')

  return exts.join('\n')
}
